### ISSUE TITLE
Closing other dropdown

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#121] opened 2017-06-21 06:46 UTC
Dropdown can closes when we click outside it (autoClose='outsideClick'), and in most cases it closes the dropdown when we open another
But we have few cases when we cannot use it
1. We use 'stopPropagation' for dropdown on click - for `semantic-ui` it's no matter, because there dropdown closes when emit 'mousedown' on document, not 'click'. Can you check if it possible to use here?
2. We open dropdown on hover (when 'hover' set 'isOpen' = true) - maybe in this case you can add condition to check if any other dropdown opened, but I'm not sure

**Comment by edcarroll** [comment] 2017-06-21 15:44
Hi there, if I've understood your questions correctly:

1. Using `stopPropagation` is generally a bad idea because it tends to break other things that rely on the event bubbling through the DOM. This library used to rely on it to ensure dropdowns worked correctly, however I moved away from it because it was causing issues elsewhere. To avoid using `stopPropagation`, you can add a boolean to `Event` called something like `myEventHandled` and setting that to true, then in your components ignore any events with that property (this is what I do in this library).
   - So, since using `stopPropagation` is a bad idea, I'd rather not change the library to support it - so will only change to mousedown if there is a good reason other than this.

2. Currently dropdowns have no idea about any other dropdowns on the page (same for all of the components). They close automatically separately from eachother, in order to allow functionality like `autoClose="disabled"`. Therefore, the other dropdowns not closing is by design, and I won't be changing this functionality I'm afraid.

However, relating to point 2, I can look into adding functionality into the library that lets you change the trigger for a dropdown - so you don't have to manually set `isOpen` on hover?

Let me know if that's something you're interested in, and I can reopen this issue with the aim of changing that functionality.

**Closed by edcarroll** 2017-06-21 15:44 UTC
Labels: component: dropdown, type: question
