### ISSUE TITLE
Bug (Tabs) : setting property value directly from html page is not working

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#244] opened 2017-08-12 09:56 UTC
I am implement tab view with displaying some tab openned whren page is loaded and facing issue. Whenever I am trying to pass TRUE value directly from HTMl page it is not working. But if I took a variable and passing TRUE value inside that variable then it works as expected.
![screenshot_1](https://user-images.githubusercontent.com/22045550/29239561-fa71c1e6-7f6e-11e7-8c5b-537a0e5a18e4.png)

Plunkr : http://plnkr.co/edit/aspIjIgVo4ZjAM3ddrci?p=preview

Angular: ^4.2.2
ng2-semantic-ui: ^0.9.3
Semantic UI: 2.2.2

**Comment by edcarroll** [comment] 2017-08-13 01:02
Hi, please could you make a plunkr reproducing this issue?

**Comment by dev-fullstacktechnology** [comment] 2017-08-19 13:09
I will do it as soon as possible. It will helpful if you provide any working plunkr link so I can directly take code structure from that.

**Comment by edcarroll** [comment] 2017-08-19 23:24
No problem, you can use [this one](http://plnkr.co/edit/SJMMMS8wQkwdX1HeMqiH?p=preview) from the issue template 😄

**Comment by dev-fullstacktechnology** [comment] 2017-08-23 12:31
Here is plunkr : 
http://plnkr.co/edit/aspIjIgVo4ZjAM3ddrci?p=preview

**Comment by edcarroll** [comment] 2017-08-26 22:33
Thank you! Though I'm opening it and getting a compilation error rather than a runtime error, please could you take a quick look?

**Comment by dev-fullstacktechnology** [comment] 2017-08-28 05:42
Yes, It is actually a problem. If I remove [(isActive)]="true" from code It works fine, Or even if I write [(isActive)]="someVar" then also it works. But, setting value true directly from UI cause an issue. And I don't want to take an extra variable in my code only for setting boolean value.

**Comment by mcosta74** [comment] 2017-08-28 06:31
Hi,
Have you tried using `[isActive]`?

**Comment by mcosta74** [comment] 2017-08-28 06:33
I mean `[isActive]="true"`.

**Comment by edcarroll** [comment] 2017-08-29 03:31
Ahhh sorry I've completely missed what's been going on here. @mcosta74 is absolutely correct, you need to use just `[isActive]` and not `[(isActive)]`.

This is because, `[(isActive)]="var"` is actually syntactic sugar for `[isActive]="var" (isActiveChange)="var = $event". When `var` is the literal `true`, `true = {true/false}` is never going to work because you can't reassign `true`.

I hope that makes sense.

**Closed by edcarroll** 2017-08-29 03:31 UTC
Labels: state: needs repro
