### ISSUE TITLE
Issue in Safari

### ISSUE THREAD

**Issue by mcosta74** [edcarroll/ng2-semantic-ui#92] opened 2017-06-06 21:13 UTC
Hi,

Just setup a simple application using you library (angular-cli based).
Everything works well in Chrome but In Safari I get this error 
![screen shot 2017-06-06 at 23 12 04](https://user-images.githubusercontent.com/3706809/26852158-a2483990-4b0d-11e7-8bb7-6c34636a878e.png)
and the application is not loading

**Comment by edcarroll** [comment] 2017-06-06 21:15
This is due to the web animations polyfill used to make the collapse component work. I've been investigating it this evening, and will be releasing `0.8.2` in a few hours, that moves the polyfill out of the bundle (which will fix this issue, and #91).

Will update this once `0.8.2` is out 😄

**Comment by mcosta74** [comment] 2017-06-06 21:17
Great news

Thanks again for this awesome tool

**Comment by edcarroll** [comment] 2017-06-07 00:26
`0.8.2` fixes this issue. Please do read [the release notes](https://github.com/edcarroll/ng2-semantic-ui/releases/tag/v0.8.2) to ensure the breaking change introduced doesn't affect you.

**Comment by mcosta74** [comment] 2017-06-07 07:12
Upgraded to 0.8.2 but still experiencing this on safari
![screen shot 2017-06-07 at 08 59 14](https://user-images.githubusercontent.com/3706809/26866002-9c0a34f0-4b5f-11e7-9863-3718fd789a7c.png)

**UPDATE:** the next screenshot is when I load the official website (https://edcarroll.github.io/ng2-semantic-ui/) with safari

![screen shot 2017-06-07 at 09 10 58](https://user-images.githubusercontent.com/3706809/26866448-6dcee08e-4b61-11e7-9e24-564911d74405.png)

**Comment by edcarroll** [comment] 2017-06-07 16:09
How strange - will update this when I know more.

**Comment by mcosta74** [comment] 2017-06-07 16:22
well, 

is it very strange. I'm pretty sure is not my app because also the "official website" cannot be loaded in safari

If you need more info (or maybe you simply cannot reproduce), please let me know

**Comment by edcarroll** [comment] 2017-06-07 18:37
So I tested the demo application in Safari on a mac, and couldn't reproduce the error oddly enough.

However, I have altered how the web animations polyfill is loaded - could you please try the demo application again on your computer to see if the error persists?

We can then go from there about sorting the issue on your local machine.

**Comment by mcosta74** [comment] 2017-06-07 19:29
Hi, 

Should I use the website or shall I clone the repository and build the demo app on myself?

I'll test as soon as possible

**Comment by edcarroll** [comment] 2017-06-07 19:30
Just the website for now

**Comment by mcosta74** [comment] 2017-06-07 19:50
I don't have my Mac right now but I tested with an iPad and I cannot load the website.
Tried also with a Windows Phone and it works

**Comment by edcarroll** [comment] 2017-06-07 20:17
Thank you for checking... it seems this one is going to be a bit more confusing than I thought! I'm trying to get hold of a mac at the moment to test things further.

**Comment by mcosta74** [comment] 2017-06-07 20:22
Small Update,

I built the demo app on my computer and ran it in `dev` mode.
Now I have console output a bit more easier to read.

![screen shot 2017-06-07 at 22 17 49](https://user-images.githubusercontent.com/3706809/26899446-6a910abe-4bcf-11e7-98a6-b3f47c7dbbd8.png)

Looks like the problem is inside the `popper.js` file used in `position.service.ts`.

So looks like not related to the polyfills

**Comment by edcarroll** [comment] 2017-06-07 20:26
The plot thickens! Could you click into the `positioning.service.ts` part of the trace to see where it is getting stuck please?

**Comment by mcosta74** [comment] 2017-06-07 20:33
done,

![screen shot 2017-06-07 at 22 30 22](https://user-images.githubusercontent.com/3706809/26899934-fba5590a-4bd0-11e7-9223-3e9af1288c2d.png)

Maybe I'm wrong (not a Javascript/TypeScript expert) but seems the issue is in the import 
```
import {ElementRef, EventEmitter} from '@angular/core';
import Popper from "popper.js";

export type PositioningPlacement = "inherit" | "top left" | "top" | "top right" | "bottom left" | "bottom" | "bottom right" | "left top" | "left" | "left bottom" | "right top" | "right" | "right bottom";
```

so something inside the `popper.js` code

**Comment by edcarroll** [comment] 2017-06-07 20:40
Ok, so maybe this is an issue with a newer version of popper.js.

Perhaps find the version of popper.js in the package.json, and install specifically that version

```bash
npm remove popper.js
npm install popper.js@specific version
```

**Comment by mcosta74** [comment] 2017-06-07 22:51
I did it but nothing changed. 

Are you sure you cannot reproduce?? (I can both on my Mac and on one iPad

**Comment by edcarroll** [comment] 2017-06-07 22:59
Still trying to get hold of a Mac - will let you know when I've managed it

**Comment by edcarroll** [comment] 2017-06-08 01:50
Right, so I've managed to get a copy of macOS up and running, and have been attempting to test the library in Safari.

So far, I have tested:

* Accessing the [current live demo project](https://edcarroll.github.io/ng2-semantic-ui)
   - No errors
* Cloning the library, and running the demo locally (with `ng serve`)
   - No errors
* Creating a brand new Angular project with the CLI, installing the library, importing the module & adding a component to the page
   - No errors
* Same as above, but using `v0.8.1`
   - No errors

For the life of me I can't seem to be able to reproduce this at all - is there any way you can send me a copy of the repo you're using so I can test it out on my machine?

Do you have any more specifics about the version of safari you're using, etc?

Hopefully we can get to the bottom of this!!

**Comment by mcosta74** [comment] 2017-06-08 06:14
Hi,

on my machine I'm using Safari 9.1 (Installed with macOS El Capitan 10.11).
Just tried a VM with macOS Sierra (10.12) and Safari 10.1 and everything works.
Also the iPad I'm using is not with the latest version of iOS.

So seems that everything works with the latest version of Safari but not with the previous versions;  this means in the app I'm writing I have to say `Safari 10+ compatible`.

In general would be nice to have a **Browser Support** matrix also in your website or at least in the github page (like the one semantic-ui has)

**Comment by edcarroll** [comment] 2017-06-08 21:36
Thank you for the info re which versions of Safari you're testing on - I'm installing an El Capitan VM now to see if I can resolve this issue - as I'd rather be able to support all of the browsers Semantic UI supports 😄 

Will see if I can fix this bug on El Capitan, then will add a browser support matrix as you've suggested for future reference.

**Comment by mcosta74** [comment] 2017-06-08 21:53
Well, in September Apple will release macOS HIgh Sierra (10.13) so your library will be compatible with the last 2 version of Safari 👍

**Comment by edcarroll** [comment] 2017-06-09 00:00
Success!! I've worked out what it was, and have pushed a fix for it.

So the error about assigning to a readonly property was actually coming from the Typescript emitted `__extends` function - in which it assigns to the object's `constructor` property. This isn't normally an issue, except in this case the class that it was trying to extend was the `Event` class.

The reason this failed in Safari (9 and below), was because Safari's `Event.prototype.constructor` is readonly.

This entire thing has cropped up because of a bug from a few weeks ago - dropdowns and selects would not close when you clicked on other dropdowns and selects, due to their use of `event.stopPropagation()` in the click handlers. This is less than ideal, so to replace those cancelled events I added a property to the `Event` class that allowed me to check whether it had already been handled by my library (and if so, ignore it). This was the nicer alternative to some quite complex DOM queries on each event.

To do this, I created 2 classes, `HandledMouseEvent` and `HandledKeyboardEvent`, which were defined:

```typescript
export class HandledMouseEvent extends MouseEvent {
    public eventHandled:boolean;
}

export class HandledMouseEvent extends KeyboardEvent {
    public eventHandled:boolean;
}
```

and then used them like so:

```typescript
@HostListener("click", ["$event"])
public onClick(e:HandledMouseEvent) {
    if (!e.eventHandled) { ... }
}
```

(I didn't use interfaces because of [this issue](https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897))

So, in order to fix this bug cropping up in Safari, I now do:

```typescript
export class HandledEvent {
    public eventHandled:boolean;
}

...
@HostListener("click", ["$event"])
public onClick(e:HandledEvent & MouseEvent) {
    if (!e.eventHandled) { ... }
}
```

Thank goodness for intersection types!

---

Thank you for all of your help getting this sorted - will be releasing this with `0.8.3` soon.

**Closed** 2017-06-09 00:03 UTC
Labels: component: collapse, priority: critical, type: bug

**Comment by edcarroll** [comment] 2017-06-09 01:09
...and the demo site seems to now be working again (had to delete and reinstall `node_modules`!)

Could you please give the site a try on an iOS device if you have one around?

**Comment by mcosta74** [comment] 2017-06-09 06:01
Hi,

Just tried with an iOS 9 device and it works.
Great Job.

Last question: my app uses `angular-cli` so I can list the `web-animation.js` library in the HTML file or embed it in my bundle. What's your suggested approach?

**Comment by edcarroll** [comment] 2017-06-12 22:28
Hey, missed your question!

So I would advise against embedding it in your bundle, because of [this issue](https://github.com/web-animations/web-animations-js/issues/46) - so best way is probably to just get angular cli to add it to the HTML file as it's own thing.

**Comment by mcosta74** [comment] 2017-06-13 06:05
Hi,

So you suggest to not include in the `polyfills.js` file used by `angular-cli` but do it directly in the index.html.
Right?

**Comment by edcarroll** [comment] 2017-06-13 06:18
Yep - don't include it in `polyfills.ts` due to the `"use strict"` bug.

Re using angular cli, I think using `scripts` has the desired effect (same as adding it to `index.html`) - though not confirmed (could you try?)

**Comment by edcarroll** [comment] 2017-06-15 06:03
`0.8.3` is now live which contains this fix.

**Comment by mcosta74** [comment] 2017-06-15 09:42
thanks, 

I tried to put `web-animations-js` in the `polyfills.ts` file and it works for Safari 9 and `v0.8.3`
