### ISSUE TITLE
support (Popup) : popup is not working

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#253] opened 2017-08-17 05:13 UTC
### Bug description:
I am trying to implement simple popup tooltip in my project. I used basic example provided in our documentation but it still not working. Any one have an idea what is the problem in my code? Here is snapshot of detail.

Component:
![screenshot_popupcode](https://user-images.githubusercontent.com/22045550/29396903-83346d4a-8338-11e7-8d43-5e5e40b0e844.png)

Import:
![screenshot_popupmodule](https://user-images.githubusercontent.com/22045550/29396907-872a0f22-8338-11e7-944a-ffdc90d084fb.png)

HTML Page:
![screenshot_popupui](https://user-images.githubusercontent.com/22045550/29396912-89d51e9c-8338-11e7-95c4-1e664ce05cb2.png)

### Version of Angular, ng2-semantic-ui, and Semantic UI:
Angular: ^4.2.2
ng2-semantic-ui: ^0.9.3
Semantic UI: 2.2.2

**Comment by edcarroll** [comment] 2017-08-17 12:38
This has been fixed in `0.9.5` - duplicate of #204

**Closed by edcarroll** 2017-08-17 12:38 UTC
Labels: comp: popup, resolution: duplicate, type: bug

**Comment by dev-fullstacktechnology** [comment] 2017-08-18 04:32
Thank You.
