### ISSUE TITLE
sui-select: AoT compilation errors

### ISSUE THREAD

**Issue by mani0608** [edcarroll/ng2-semantic-ui#49] opened 2017-03-27 06:48 UTC
I am using sui-select component along with angular 2.4.x. I am using the AoT compilation to build the components for production using the NGC command. I am getting a number of errors related to Private variables and Syntax mismatch. Attached the error file herewith.

@edcarroll Can you please help.
[sui-select-error.txt](https://github.com/edcarroll/ng2-semantic-ui/files/871656/sui-select-error.txt)

Inside systemjs
```
map: {
 'ng2-semantic-ui': 'npm:ng2-semantic-ui',
}
```

```
packages: {
 'ng2-semantic-ui': {
        main: 'index.js',
        defaultExtension: 'js'
      }
}
```

**Comment by mani0608** [comment] 2017-03-27 13:03
As a further update, the combination of systemjs & AoT compilation has lot of problems.

**Comment by edcarroll** [comment] 2017-03-27 21:18
I've done some investigation and it seems to be an issue with the angular compiler `ngc` not generating the `.ngfactory.ts` files with support for generic types. This has been fixed in Angular 4, so I've updated the library's dependencies, and will be publishing a new version on npm tomorrow.

**Comment by mani0608** [comment] 2017-03-28 08:13
Moreover, when i compile the modules using tsc, i am receiving some errors related to 

> require 

variable declaration. 

> I came to know that you have included both node and requirejs types in **_Dev-Dependencies_**

 and there seems to be the conflict. 
I'm currently not sure how to overcome this.
Also, you have included the @types as a part of Dev-Dependency. But i suppose it has to be in runtime dependency as we, the users, need these dependencies to be downloaded along with ng2-semantic-ui modules. Please correct me in case i am wrong.

**Comment by edcarroll** [comment] 2017-03-28 08:23
Could you create a repo that I can clone so I can reproduce the errors you're getting please? That will make it easier for me to work out exactly what is happening 😄

**Comment by mani0608** [comment] 2017-03-28 08:58
Sure. I will. But sadly, i am not supposed to share the source due to client policy. I will share all the rest of the configuration files.
Also, I am at work. Please give me some time and thanks for the support.

**Comment by edcarroll** [comment] 2017-03-28 09:15
No problem - I'm happy for it to be as bare bones as you need so long as it displays the issue :)

**Comment by mani0608** [comment] 2017-03-28 10:49
@edcarroll here is the link
https://github.com/mani0608/mani-ngsemantic.git

**Comment by edcarroll** [comment] 2017-03-28 12:33
I've taken a look, and have updated the develop branch with a potential solution - however I don't yet know if it works for AoT, as your repo doesn't have that included. Could you please add the failing AoT build to your repo so I can test against it?

Thanks!

**Comment by mani0608** [comment] 2017-03-28 12:51
Oh Sorry. I removed it by mistake. Let me add the AoT scripts to Gulp

**Comment by mani0608** [comment] 2017-03-28 13:18
I tried to run the AoT build against the sample repository i shared, but the build completes successfully now, for some reason. I will try it with my application and get back to you.

**Comment by edcarroll** [comment] 2017-03-28 13:19
Would be handy to still have the AoT files to test personally please - as I've drastically changed the build 😄

**Comment by mani0608** [comment] 2017-03-28 13:24
I would be happy to share the files :)
I have uploaded the files to the repository :)

**Closed** 2017-03-28 13:40 UTC

**Comment by edcarroll** [comment] 2017-03-28 13:45
I believe this issue is now sorted. Update your ng2-semantic-ui to `0.6.1` and then do the following:

* Remove all individual component references in `systemjs.config.js`.
* Change the `ng2-semantic-ui` line to be: `'ng2-semantic-ui': 'npm:ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js'`.
* Remove the reference to `element-closest` in that same file.
* Remove `<script type="text/javascript" src="./bower_components/semantic/dist/semantic.js"></script>` from `index.html`
* Add `<link rel="stylesheet" href="./bower_components/semantic/dist/semantic.min.css">` to `index.html`

You should now be able to build it without AoT, and I think the only things blocking the AoT build are some erroneous settings in your config not to do with this library.

**Comment by edcarroll** [comment] 2017-03-28 14:20
Ah yes - so the bundle `ng2-semantic-ui.umd.min.js` contains that module, as well as `popper.js`, hence not needing to reference it anymore in the SystemJS Config :)

**Comment by edcarroll** [comment] 2017-03-28 16:10
did you clone the latest version in a dev environment or install via npm? If cloning, run `npm run build`, if from npm, make sure you've updated the deps in `package.json` - `^0.5.5` won't match the latest version (`0.6.1`)

**Comment by mani0608** [comment] 2017-03-28 16:11
I am sorry. I updated it again to 0.6.1 and now its working fine.... :)

**Comment by edcarroll** [comment] 2017-03-28 16:13
Glad it's all sorted! 🎉

**Comment by mani0608** [comment] 2017-03-29 06:46
@edcarroll  mate sorry to bug you again. Now the dev build with TSC works perfectly fine and smooth. But when i do an AoT compilation, i ended up with the following error, 

> Error: 'default' is not exported by node_modules\popper.js\dist\popper.es5.js

I can see you use this inside your component. When i further investigated, it looks like you setting the path to the popper-override inside tsconfig.json
I tried adding the path 

> node_modules/popper.js/**

to my rollup commonjs script, but i ended up with the following errors

> 'default' is not exported by 'node_modules\@angular\core\@angular\core.es5.js'
'default' is not exported by 'node_modules\@angular\common\@angular\common.es5.js'
'default' is not exported by 'node_modules\@angular\animations\@angular\animations.es5.js'
'default' is not exported by 'node_modules\@angular\forms\@angular\forms.es5.js'
'default' is not exported by 'node_modules\@angular\router\@angular\router.es5.js'
'default' is not exported by 'node_modules\@angular\platform-browser\@angular\platform-browser.es5.js'

Am i missing anything here.

**Comment by edcarroll** [comment] 2017-03-29 16:20
Got a notification about an issue with `tsc` but can't find it - I assume that means all sorted?

**Comment by mani0608** [comment] 2017-03-29 17:58
Yes mate. Everything is perfectly fine. I came across any issue with popper.js 

> default is not exported by popper.es5.js

I did some investigation in your source and understood that I have to add the path of popper.js to rollup commonjs includes. 
I did that and everything is perfectly fine then. So I removed my comment here 👍👍
