### ISSUE TITLE
Searchable select issue

### ISSUE THREAD

**Issue by claudiu909** [edcarroll/ng2-semantic-ui#315] opened 2017-10-12 09:32 UTC
### Bug description:

When doing a search the select items are not displaying properly. Also the "No results" is showing whitout removing the items from the view.

Can anyone have a look at this plunker? Am I doing smth wrong?

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/U0gPUb8fMA6qLe6iezqi?p=preview

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular:
4.3.5
ng2-semantic-ui:
0.9.6
Semantic UI:
2.2.12

Thanks

**Comment by gobeli** [comment] 2017-10-12 14:59
Have a look at the [docs](https://edcarroll.github.io/ng2-semantic-ui/#/modules/select). You need to set the `options` attribute of your select and then loop through the provided `filteredOptions` property of the select:

```html
<sui-select class="selection fluid" name="productUm"
		[(ngModel)]="um_id"
		[isSearchable]="true"
		[options]="ums"
		valueField="id"
		labelField="name"
		#selectUm>
	<sui-select-option *ngFor="let um of selectUm.filteredOptions" [value]="um"></sui-select-option>
</sui-select>
```

**Comment by claudiu909** [comment] 2017-10-12 15:28
@gobeli Many thanks! 

One more thing: There is any way to set "fullTextSearch" as true? Sorry but I don't get it from docs.

Thanks!

**Comment by gobeli** [comment] 2017-10-13 06:20
You could try to use the `optionsFilter ` attribute

**Comment by edcarroll** [comment] 2018-03-16 23:31
Going to close this for now, looks like the issue is sorted. You can reopen if you have another question!

**Closed by edcarroll** 2018-03-16 23:31 UTC
Labels: comp: select, type: question
