### ISSUE TITLE
Performance issue with ng2-Semantic dropdown and Tooltip

### ISSUE THREAD

**Issue by preethis610** [edcarroll/ng2-semantic-ui#345] opened 2018-02-09 11:41 UTC
I used the code sample from the documentation. It is working fine with a single dropdown/tooltip. When I use more number of Dropdowns in a component, it is affecting the entire project.Performance is poor and I couldn't able to type in the input fields of even other components, I am getting "[Violation] 'keydown' handler took 3141ms" in Verbose mode.Using more number of tooltips is showing [Violation] 'click' handler took 624ms, when I click anywhere in the project.Could anyone give me a solution.

**Comment by NikhilRadadiya** [comment] 2018-02-14 13:03
@preethis610 Having same issue, seems like I have to change the component

**Comment by edcarroll** [comment] 2018-03-17 00:03
Closing as duplicate of #284

**Closed by edcarroll** 2018-03-17 00:03 UTC
Labels: comp: dropdown, comp: popup, resolution: duplicate, type: bug
