### ISSUE TITLE
Wide tab elegant way placement

### ISSUE THREAD

**Issue by DrWifey** [edcarroll/ng2-semantic-ui#324] opened 2017-11-14 13:51 UTC
Do you consider making possibility of automatic appearance of arrows when tabs becoming too wide (like in Firefox browser) or some other elegant way to hide tabs that don't fit the screen? Thanks.

**Comment by edcarroll** [comment] 2018-03-16 23:41
Duplicate of #115, as this can be solved entirely using CSS it's out of the scope of this library and needs to be taken up with Semantic UI ([issue exists here](https://github.com/Semantic-Org/Semantic-UI/issues/3076)).

Alternatively, use a `stackable tabs menu` to make the tabs stack on overflow.

**Closed by edcarroll** 2018-03-16 23:41 UTC
Labels: comp: tabs, resolution: duplicate, type: question
