### ISSUE TITLE
Modal doesn't working Getting error - ERROR TypeError: Hu.c is not a constructor

### ISSUE THREAD

**Issue by smartHasmukh** [edcarroll/ng2-semantic-ui#306] opened 2017-09-25 03:43 UTC
When I have created build using `ng build --target=production`  then modal doesn't worked

![1](https://user-images.githubusercontent.com/8941195/30791670-a57bf294-a1d1-11e7-94cc-5e2f0bf5f713.png)

`ERROR TypeError: Hu.c is not a constructor
    at n.onDeletePromoCode (main.3b4fab534600a14150d8.bundle.js:1)
    at Object.handleEvent (main.3b4fab534600a14150d8.bundle.js:1)
    at Object._ [as handleEvent] (vendor.4d85aebdfdf63354bfff.bundle.js:1)
    at Object.handleEvent (vendor.4d85aebdfdf63354bfff.bundle.js:1)
    at ie (vendor.4d85aebdfdf63354bfff.bundle.js:1)
    at vendor.4d85aebdfdf63354bfff.bundle.js:1
    at HTMLSpanElement.<anonymous> (vendor.4d85aebdfdf63354bfff.bundle.js:1)
    at e.invokeTask (polyfills.c9b879328f3396b2bbe8.bundle.js:1)
    at Object.onInvokeTask (vendor.4d85aebdfdf63354bfff.bundle.js:1)
    at e.invokeTask (polyfills.c9b879328f3396b2bbe8.bundle.js:1)`

**Comment by Potapy4** [comment] 2017-09-25 19:10
Duplicate of #301

**Comment by edcarroll** [comment] 2018-03-16 23:38
Closing as it is indeed a duplicate.

**Closed by edcarroll** 2018-03-16 23:38 UTC
Labels: comp: modal, resolution: duplicate, type: bug
