### ISSUE TITLE
bug(Tabs) : Overflowing tabs on space limitation

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#219] opened 2017-08-08 06:33 UTC
I have more then 5 tabs on single page of my project. When I switched on tablet mode, the tabs making overflow out of screen. I also checked on our github code and documentation site and I found we have bug in our code. here is snapshot of bug.
![overflow_tabs](https://user-images.githubusercontent.com/22045550/29058895-806c5adc-7c30-11e7-8757-66b1cf079182.png)
I suggest we can make tabs scrollable horizontally when it overflows without showing scrollbar. 

Angular: ^4.2.2
ng2-semantic-ui: ^0.9.3
Semantic UI: 2.2.2

**Comment by edcarroll** [comment] 2017-08-08 21:27
Duplicate of #115, as this can be solved entirely using CSS it's out of the scope of this library and needs to be taken up with Semantic UI ([issue exists here](https://github.com/Semantic-Org/Semantic-UI/issues/3076)).

Alternatively, use a `stackable tabs menu` to make the tabs stack on overflow.

**Closed by edcarroll** 2017-08-08 21:27 UTC
Labels: state: investigating

**Comment by kuroshhashemi** [comment] 2017-08-12 22:47
If this can be solved entirely using CSS, can someone please post how to do so?  This same issue has been opened by multiple people and there's clearly some guidance needed on how best to navigate around the challenge.  We (the non-CSS-experts) would very much appreciate it

**Comment by edcarroll** [comment] 2017-08-13 00:58
@kuroshhashemi apologies for the lack of clarity here, essentially when I was saying it needs to be solved with CSS I was meaning that an issue should be opened on the Semantic UI repo as a feature request / bug report.

As for implementing it yourself, try adding an `overflow-x: auto` to the tab header menu, which should (*I think*) add scrolling support. Though bear in mind if it does work it won't look great on desktop as the scrollbar will appear in a potentially unsightly place.

I hope that's helped a bit - let me know if you have further questions 😄
