### ISSUE TITLE
Question - Why not work with/join ngSemantic?

### ISSUE THREAD

**Issue by Martin-Andersen** [edcarroll/ng2-semantic-ui#37] opened 2016-11-13 10:33 UTC
I was looking for a css framework for my new Angular 2.0 project and decided on Semantic UI then I looked for Angular integration and found ng-semantic-ui and [ngSemantic](https://github.com/vladotesanovic/ngSemantic).
I don't know the history of each project but for an outsider it looks like the two projects has the same purpose and goal, so why not join forces?

**Comment by vazh** [comment] 2016-11-15 08:55
@Martin-Andersen 
i personally dont know why,
but this is an angular2 native implementation of semantic-ui.
so no jquery.

while ngSemantic use jQuery.

**Comment by mikalben** [comment] 2017-01-29 01:18
@vazh  @Martin-Andersen  I haven't yet looked at the source code of either repositories, but "lon-yang/angular2-semantic-ui" mentioned above, seem to contain the exact same components as this one, and not much have been done on it (1 contributor, 1 branch, 0 issues++) ...  maybe a clone of this rep?

This project is certainly something I would be interested in contributing to. The reason I wouldn't use the main project (ngSemantic), is because of its dependency on jQuery, which is a no-go for me - any many others I assume.

**Comment by borisfeldmann** [comment] 2017-03-20 08:59
Hey @Martin-Andersen, hey @vazh, I also would like to contribute with my team, because I think Semantic UI is a great an feature-rich CSS framework. On the other hand, Angular2 is awesome and keeping a dependency to jQuery in an Angular2 project seems to be quite wrong. We have tested ng-semantic as well as a pure integration of Semantic-UI with CSS an JavaScript and some own directives to make it work. But you quickly run into problems caused by jQuery. 

So, it would be really great to have a jQuery-free full implementation of Semantic UI in Angular2. We'll give ng2-semantic-ui a test-drive this week and come back to you with pull requests if it works for us generally.

**Comment by edcarroll** [comment] 2017-03-22 06:49
Hi all, so essentially as you've mentioned it is because this project is a re-implementation of a set of the SUI components in pure Angular 2, whereas ngSemantic just wraps the existing jQuery implementation. I've spoken at length with the maintainer of ngSemantic about the two projects and we decided it would be best to keep them separate as they have fundamentally different goals. I'm going to close this one and reopen if anything further happens regarding the two projects.

@borisfeldmann please give 0.5.0 (released just now) a test drive, as that contains better implementations of dropdowns, searches, selects and transitions, and adds the popup component to enable tooltips.

**Closed by edcarroll** 2017-03-22 06:49 UTC
